package com.example.home.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.home.bean.EquipmentBean;

import com.example.home.db.EquipmentBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig equipmentBeanDaoConfig;

    private final EquipmentBeanDao equipmentBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        equipmentBeanDaoConfig = daoConfigMap.get(EquipmentBeanDao.class).clone();
        equipmentBeanDaoConfig.initIdentityScope(type);

        equipmentBeanDao = new EquipmentBeanDao(equipmentBeanDaoConfig, this);

        registerDao(EquipmentBean.class, equipmentBeanDao);
    }
    
    public void clear() {
        equipmentBeanDaoConfig.clearIdentityScope();
    }

    public EquipmentBeanDao getEquipmentBeanDao() {
        return equipmentBeanDao;
    }

}
