package com.example.home.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.home.bean.EquipmentBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "EQUIPMENT_BEAN".
*/
public class EquipmentBeanDao extends AbstractDao<EquipmentBean, Long> {

    public static final String TABLENAME = "EQUIPMENT_BEAN";

    /**
     * Properties of entity EquipmentBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Img = new Property(2, String.class, "img", false, "IMG");
        public final static Property Status = new Property(3, String.class, "status", false, "STATUS");
        public final static Property Catgeory = new Property(4, String.class, "catgeory", false, "CATGEORY");
        public final static Property UserTime = new Property(5, String.class, "userTime", false, "USER_TIME");
    }


    public EquipmentBeanDao(DaoConfig config) {
        super(config);
    }
    
    public EquipmentBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"EQUIPMENT_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"IMG\" TEXT," + // 2: img
                "\"STATUS\" TEXT," + // 3: status
                "\"CATGEORY\" TEXT," + // 4: catgeory
                "\"USER_TIME\" TEXT);"); // 5: userTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"EQUIPMENT_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, EquipmentBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String img = entity.getImg();
        if (img != null) {
            stmt.bindString(3, img);
        }
 
        String status = entity.getStatus();
        if (status != null) {
            stmt.bindString(4, status);
        }
 
        String catgeory = entity.getCatgeory();
        if (catgeory != null) {
            stmt.bindString(5, catgeory);
        }
 
        String userTime = entity.getUserTime();
        if (userTime != null) {
            stmt.bindString(6, userTime);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, EquipmentBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String img = entity.getImg();
        if (img != null) {
            stmt.bindString(3, img);
        }
 
        String status = entity.getStatus();
        if (status != null) {
            stmt.bindString(4, status);
        }
 
        String catgeory = entity.getCatgeory();
        if (catgeory != null) {
            stmt.bindString(5, catgeory);
        }
 
        String userTime = entity.getUserTime();
        if (userTime != null) {
            stmt.bindString(6, userTime);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public EquipmentBean readEntity(Cursor cursor, int offset) {
        EquipmentBean entity = new EquipmentBean( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // img
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // status
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // catgeory
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // userTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, EquipmentBean entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setImg(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setStatus(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCatgeory(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setUserTime(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(EquipmentBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(EquipmentBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(EquipmentBean entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
